---
- name: Configure Raspberry Pi 5 to use the drive attached to the NVMe Base.
  hosts: raspberrypi
  become: true
  tasks:
    #
    # Enable PCIe gen3 for the NVMe drive on a Pimoroni NVMe Base.  We do not do this
    # on the NVMEBse Duo as it is not supported.
    #
    - name: Ensure pciex1_gen3 is enabled in /boot/firmware/config.txt
      blockinfile:
        path: /boot/firmware/config.txt
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          dtparam=pciex1_gen=3
        insertafter: '^\[all\]$'
        create: yes
      when: not nvme_duo

    #
    # Configure the drive on the NVMeBase and the first drive on the NVMeBase Duo.
    #
    - include_tasks: ConfigureNVMeDriveTasks.yml
      vars:
          nvmebase_device_name: nvme0n1

    #
    # Configure the second drive on the NVMeBase Duo.
    #
    - include_tasks: ConfigureNVMeDriveTasks.yml
      vars:
          nvmebase_device_name: nvme1n1
      when: nvme_duo == true

    #
    # Not strictly needed but it will allow us to check if the drive(s) have been mounted correctly
    # and can be seen after a reboot.
    #
    - name: Reboot the Raspberry Pi
      reboot:
        msg: "Immediate reboot initiated by Ansible"
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 0
