---
- name: Update the Raspberry Pi 5 OS and reboot
  hosts: raspberrypi
  become: true
  tasks:
    #
    # Update the system software.
    #
    - name: Update apt caches and the distribution
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        autoclean: yes
        autoremove: yes
        
    #
    # Configure the system to use the latest boot ROM.
    #
    - name: Update the EEPROM
      command: raspi-config nonint do_boot_rom E1 1

    #
    # Reboot to apply changes.
    #
    - name: Reboot the Raspberry Pi
      reboot:
        msg: "Immediate reboot initiated by Ansible"
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 0
